apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-ms
  template:
    metadata:
      labels:
        app: java-ms
    spec:
      containers:
      - name: java-ms
        image: 250919241461.dkr.ecr.us-east-1.amazonaws.com/tessolve-ecr:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080