apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-ms
  
  labels:
    app: nodejs-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-ms
  template:
    metadata:
      labels:
        app: nodejs-ms
    spec:
      containers:
      - name: nodejs-ms
        image: 250919241461.dkr.ecr.us-east-1.amazonaws.com/tessolve-ecr:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m" #half the CPU free: 0.5 Core
            memory: "256Mi"
          limits:
            cpu: "1000m" #max 1.0 Core
            memory: "512Mi"
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: nodejs-ms-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: nodejs-ms-config
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: nodejs-ms-config
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: nodejs-ms-config
                key: DB_PORT
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: nodejs-ms-config
                key: DB_HOST
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP